name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    name: Check Tests
    steps:
      - name: Check Tests
        uses: actions/checkout@v3
        run: vendor/bin/pest
